// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using forthekittens.DataAccess.Data;

#nullable disable

namespace forthekittens.DataAccess.Migrations
{
    [DbContext(typeof(Kittensdbcontext))]
    [Migration("20231203120303_ImageUrlAddedAndSeeded")]
    partial class ImageUrlAddedAndSeeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("forthekittens.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Apparels"
                        });
                });

            modelBuilder.Entity("forthekittens.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListPrice")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Price10")
                        .HasColumnType("int");

                    b.Property<int>("Price5")
                        .HasColumnType("int");

                    b.Property<string>("Product_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "",
                            ListPrice = 400,
                            Manufacturer = "JoyfulPets Creations",
                            Price = 350,
                            Price10 = 3000,
                            Price5 = 1500,
                            Product_description = "A vibrant, rainbow-colored ball toy with attached feathers, designed to engage your cat in playful activities.",
                            Product_name = "Rainbow Whisker Ball Toy",
                            Upc = "111222333444"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "",
                            ListPrice = 799,
                            Manufacturer = "Paws & Whiskers Co.",
                            Price = 600,
                            Price10 = 5000,
                            Price5 = 2500,
                            Product_description = "A multi-level cat tree condo with scratching posts, cozy hideaways, and dangling toys.",
                            Product_name = "Cat Haven Deluxe Tree",
                            Upc = "123456789012"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageUrl = "",
                            ListPrice = 899,
                            Manufacturer = "DreamyPets Couture",
                            Price = 700,
                            Price10 = 6000,
                            Price5 = 3000,
                            Product_description = "A hammock-style bed for cats with a fluffy pillow, creating a cozy spot for your cat to nap in style.",
                            Product_name = "Sweet Dreams Cat Hammock",
                            Upc = "222333444555"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ImageUrl = "",
                            ListPrice = 1999,
                            Manufacturer = "Meow Mix Delights",
                            Price = 1500,
                            Price10 = 10000,
                            Price5 = 5000,
                            Product_description = "A high-quality, grain-free cat food with a blend of premium ingredients for a happy and healthy cat.",
                            Product_name = "Gourmet Purrfection Cat Cuisine",
                            Upc = "234567890123"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ImageUrl = "",
                            ListPrice = 449,
                            Manufacturer = "SnugglePaws Co.",
                            Price = 400,
                            Price10 = 3600,
                            Price5 = 1800,
                            Product_description = "A super-soft plush blanket with a cute paw print design, providing warmth and comfort for your cat.",
                            Product_name = "WhiskerWonder Plush Blanket",
                            Upc = "333444555666"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ImageUrl = "",
                            ListPrice = 499,
                            Manufacturer = "Whisker Wonders Ltd.",
                            Price = 450,
                            Price10 = 3600,
                            Price5 = 2000,
                            Product_description = "A set of interactive toys, including feather wands, laser pointers, and treat-dispensing balls, to keep your cat entertained for hours.",
                            Product_name = "Playful Paws Interactive Toy Set",
                            Upc = "345678901234"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            ImageUrl = "",
                            ListPrice = 299,
                            Manufacturer = "ChicKitty Accessories",
                            Price = 250,
                            Price10 = 1800,
                            Price5 = 1000,
                            Product_description = "A set of adorable ceramic cat bowls with cute cat illustrations, perfect for serving your cat's meals in style.",
                            Product_name = "Cute Kitty Ceramic Bowl Set",
                            Upc = "444555666777"
                        });
                });

            modelBuilder.Entity("forthekittens.Models.Product", b =>
                {
                    b.HasOne("forthekittens.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
